name: Swift test Package

on: [push]

jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build for macOS
      run: swift build -v
    - name: Run macOS tests
      run: swift test -v
